default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: darelvc_kopilka
  username: kopilka_rec
  password: dkvs43gh4
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  database: kopilka_prod
  username: kopilka_rec
  password: dkvs43gh4
