# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 052cbe123a9bddd7c02a82e03657ed8878695baa655f2946d44121755a9470ed060d2a828e50d682091de7eebfcf8a74e7f7bb3e6e4e8872b87cd462fe8a77e7

test:
  secret_key_base: 40fbd89727aeca40ed6cb42dbfaa13155b60520b5c5b0b9a7261d3c1af75e624cc1ed520355ed1ca95b950d03715a334ac5047d5af864d1b6d2c53f8a2b1bd37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
